spring:
  application:
    name: eureka
server:
  port: ${PORT:8761}
shell:
  ssh:
    port: 2010
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
security:
  user:
    name: ${eureka.username:vennetics}
    password: ${eureka.password:M5NLqZD8ivv0}